"""
Django settings for lykchat project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from library.config.database import redis_config
from library.utils.time_conv import timestamp2datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '((rp4ee+s3pyf1!a-3&a%b#l@8m!scqum&a5=94&qg&cfq8gqn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'lykchat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lykchat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "templates/"),
            os.path.join(BASE_DIR, "templates/sysadmin"),
            os.path.join(BASE_DIR, "templates/wechat"),
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'lykchat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
'''

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'
# LANGUAGE_CODE = 'zh-hans'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

# USE_TZ = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static/"),
]

MEDIA_ROOT = os.path.join(BASE_DIR, "file/")

# 媒体文件的相对路径：
MEDIA_URL = '/file/' 

# 设置静态文件路径
STATIC_PATH = os.path.join(BASE_DIR, "file/")

'''
sess_redis_conf = redis_config['default']
SESSION_COOKIE_AGE = 60 * 60 * 4
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'
SESSION_ENGINE = 'redis_sessions.session'
SESSION_REDIS_HOST = sess_redis_conf['host']
SESSION_REDIS_PORT = sess_redis_conf['port']
SESSION_REDIS_DB = sess_redis_conf['db']
SESSION_REDIS_PASSWORD = sess_redis_conf['pwd']
SESSION_REDIS_PREFIX = 'lykchat:session'
'''

sess_redis_conf = redis_config['default']
SESSION_ENGINE = 'redis_sessions.session'
SESSION_COOKIE_AGE = 60 * 60 * 4
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # 关闭浏览器，则COOKIE失效
SESSION_REDIS = {
    'host': sess_redis_conf['host'],
    'port': sess_redis_conf['port'],
    'db': sess_redis_conf['db'],
    'password': sess_redis_conf['pwd'],
    'prefix': 'lykchat:session',
    'socket_timeout': redis_config['socket_timeout']
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
       'standard': {
            'format': '%(asctime)s %(pathname)s:%(lineno)d %(module)s:%(funcName)s %(levelname)s %(message)s'
        },  # 日志格式
       'min': {
            'format': '%(asctime)s %(levelname)s %(message)s'
        }  # 日志格式   
    },
    'filters': {
    },
    'handlers': {
        'default': {
            'level':'INFO',  # 允许保存日志的最低级别
            'class':'logging.handlers.RotatingFileHandler',
            # 'class':'logging.handlers.TimedRotatingFileHandler',
            'filename': BASE_DIR + '/logs/lykchat_' + timestamp2datetime(fmt='%Y-%m-%d') + '.log',  # 日志输出文件
            'formatter':'standard',  # 使用哪种formatters日志格式
        },
        'wechat': {
            'level':'INFO',  # 允许保存日志的最低级别
            'class':'logging.handlers.RotatingFileHandler',
            # 'class':'logging.handlers.TimedRotatingFileHandler',
            'filename': BASE_DIR + '/logs/wechat_' + timestamp2datetime(fmt='%Y-%m-%d') + '.log',  # 日志输出文件
            'formatter':'standard',  # 使用哪种formatters日志格式
        },
    },
    'loggers': {
        'default': {
            'handlers': ['default'],
            'level': 'INFO',
            'propagate': False 
        },
        # 默认方式        
        'wechat': {
            'handlers': ['wechat'],
            'level': 'INFO',
            'propagate': False 
        },
        # 默认方式
    } 
}

